/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyWeb": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "OpenAIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PineConeKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RedisKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RedisPort": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RedisUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RedisUser": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
